name: generationModel
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - black
  - h5py
  - music21
  - pylint
  - pyngrok
  - pip
  - pip:
    - tensorflow
    - random-word
    - checksumdir
    - wget

